### ISSUE TITLE
感谢大佬的项目

### ISSUE THREAD

**Issue by Fromnowon** [fantasylw/vue-monaco-editor-zh#1]
运行时发现一些错误
![image](https://user-images.githubusercontent.com/2792725/114478279-78900600-9c30-11eb-98cd-a71f77e6a761.png)
这段代码，一是会报const常量赋值错误，二是typeof似乎都返回false，三是第二个width应该是height

**Comment by fantasylw** [comment]
哈, 过奖了, 我不是大佬啊. (设置了常量竟然还去修改这个低级错误都犯了)
由于我很少用number来设置编辑框需要多大, 所以没留意到这几行存在bug. 
谢谢你的提醒.
